<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;
use Naif\Toggle\Toggle;
use Techouse\IntlDateTime\IntlDateTime as DateTime;

class ClientSpouseConsent extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\ClientSpouseConsent::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
//    public static $title = 'id';

    public function title()
    {
        return  $this->notary->surname_n . " " . $this->notary->short_name . " " . $this->notary->short_patronymic
            . " " . $this->client_spouse->surname_n . " " . $this->client_spouse->name_n . " " . $this->client_spouse->patronymic_n
            . " " . $this->reg_num;
    }

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    public static $group = "Угода";

    public static function label()
    {
        return "Згода"; // TODO: Change the autogenerated stub
    }

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            BelongsTo::make('Шаблон згоди', 'consents_template', 'App\Nova\ConsentTemplate'),
            BelongsTo::make('Нотариус', 'notary', 'App\Nova\Notary'),
            BelongsTo::make('Подружжя клієнта', 'client_spouse', 'App\Nova\ClientSpouse'),

            BelongsTo::make('Тип шлюбного свідоцтва', 'marriage_type', 'App\Nova\MarriageType'),
            Text::make('Серія свідоцтва', 'mar_series'),
            Text::make('Номер свідоцтва', 'mar_series_num'),
            DateTime::make('Виданий', 'mar_date'),
            Text::make('Орган, що видав', 'mar_depart'),
            Text::make('Реєстраційний номер шлюбу', 'mar_reg_num'),

            DateTime::make('Дата підписання згоди', 'date'),
            Text::make('Номер реєстрації у нотаріуса', 'reg_num'),
            Toggle::make('Активн згода', 'active'),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
