<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;
use Techouse\IntlDateTime\IntlDateTime as DateTime;
use OptimistDigital\NovaSortable\Traits\HasSortableRows;

class ImmovableOwnership extends Resource
{
    use HasSortableRows;
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\ImmovableOwnership::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'registration_number';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    // public static $group = "Об'єкт";
    public static $group = "Перевірки";

    public static function label()
    {
        return "Право власності"; // TODO: Change the autogenerated stub
    }

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            BelongsTo::make('Нерухомість', 'immovable', 'App\Nova\Immovable'),
            Text::make('Номер права власності', 'gov_reg_number')->rules('required'),
            DateTime::make('Дата права власності', 'gov_reg_date')->required()->locale('uk'),
            Text::make('Номер витягу на право власності', 'discharge_number'),
            DateTime::make('Дата витягу на право власності', 'discharge_date')->format('DD.MM.YYYY')->required()->locale('uk'),
            BelongsTo::make('Відповідальний', 'discharge_resp', 'App\Nova\Notary'),
//            Text::make('Реєстраційний номер об’єкта нерухомого майна', 'registration_number')->rules('required'),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
