<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

class NumericConvert extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\NumericConvert::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    public static $group = "Конвертація";

    public static function label()
    {
        return "Числа"; // TODO: Change the autogenerated stub
    }

    public static function singularLabel()
    {
        return parent::singularLabel(); // TODO: Change the autogenerated stub
    }

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            Text::make('Пропис цифрою', 'original')->creationRules('unique:numeric_converts,original')->updateRules('unique:numeric_converts,original,{{resourceId}}'),
            Text::make('Назва у називному відмінку', 'title_n')->creationRules('unique:numeric_converts,title_n')->updateRules('unique:numeric_converts,title_n,{{resourceId}}'),
            Text::make('Назва у родовому відмінку', 'title_r'),
            Text::make('Назва у давальному відмінку', 'title_d'),
            Text::make('Назва у знахідному відмінку', 'title_z'),
            Text::make('Назва у орудному відмінку', 'title_o'),
            Text::make('Назва у місцевому відмінку', 'title_m'),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
