# This is a basic workflow to help you get started with Actions

name: Build-Frontend-Application 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./front

    steps:
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
